os:
  - linux
sudo: required
dist: trusty
dart:
  - 2.1.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone --single-branch https://github.com/flutter/flutter.git -b stable
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - flutter test
cache:
  directories:
    - $HOME/.pub-cache