name: typicons_flutter
description: Typicons pack with the code to support flutter, easy use, beautifully.
version: 0.4.1
homepage: https://github.com/tvc12/typicons_flutter
repository: https://github.com/tvc12/typicons_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
flutter:
  fonts:
    - family: Typicons
      fonts:
        - asset: fonts/typicons.ttf
